manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Topher083 
      url-base: https://github.com/Topher083
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem 
      remote: Topher083
      revision: main
  self:
    path: config
